[package]
name = "dmenu_launch"
version = "0.1.0"
authors = ["Vendicated <vendicated@riseup.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
